filterEnabled: true
lang: en
logOriginalFilteredMessage: true
blockFilteredMessage: false
useIgnorePermission: true
filterString: "***"
upcaseFilter: true
upcaseMinAmount: 5
upcaseFilterPattern: "[A-Z\u00C1\u00C9\u00CD\u00D3\u00DA\u00D1]"
ipFilter: true